apiVersion: v1
kind: Service
metadata:
  name: neo4jpublic
  labels:
    app: neo4j
    component: core
spec:
  ports:
    - port: 80
      targetPort: 7474
      name: browser
    - port: 6362
      targetPort: 6362
      name: backup
    - port: 7687
      targetPort: 7687
      name: bolt
  type: LoadBalancer
  selector:
    app: neo4j
    component: core